/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// The Supabase CLI scaffolds this helper, so we centralize env lookups here.
const envProjectId = import.meta.env.VITE_SUPABASE_PROJECT_ID ?? "";
const envAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

if (!envProjectId || !envAnonKey) {
	console.warn("Supabase environment variables are not configured.");
}

export const projectId = envProjectId;
export const publicAnonKey = envAnonKey;